name: Notify Parent Repository
on:
  push:
    branches: [ master ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Parent Repository Update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: jthebest/pavimentos
          event-type: submodule-updated
          client-payload: '{"submodule": "pavimentos-i18n", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'