name: Notify Parent Repository
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Git authentication
        run: |
          git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Trigger parent update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: jthebest/pavimentos
          event-type: submodule-updated
          client-payload: |
            {
              "submodule": "pavimentos-i18n",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "message": "${{ github.event.head_commit.message || 'No commit message' }}",
              "author": "${{ github.event.head_commit.author.name || 'Unknown' }}",
              "timestamp": "${{ github.event.head_commit.timestamp || '' }}",
              "run_id": "${{ github.run_id }}"
            }